/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/EG4S20/AN5640/al_ip/video_pll.v
 ** Date	:	2025 09 09
 ** TD version	:	6.2.168116
************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:                50.000000MHz
//	Clock multiplication factor: 4
//	Clock division factor:       3
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 66.666667 MHZ	| 0.0000  DEG  
//		C1        	| 333.333333MHZ	| 0.0000  DEG  
//		C2        	| 23.809524 MHZ	| 0.0000  DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module video_pll (
  refclk,
  reset,
  clk0_out,
  clk1_out,
  clk2_out 
);

  input refclk;
  input reset;
  output clk0_out;
  output clk1_out;
  output clk2_out;

  wire clk0_buf;

  EG_LOGIC_BUFG bufg_feedback (
    .i(clk0_buf),
    .o(clk0_out) 
  );

  EG_PHY_PLL #(
    .DPHASE_SOURCE("DISABLE"),
    .DYNCFG("DISABLE"),
    .FIN("50.000000"),
    .FEEDBK_MODE("NORMAL"),
    .FEEDBK_PATH("CLKC0_EXT"),
    .STDBY_ENABLE("DISABLE"),
    .PLLRST_ENA("ENABLE"),
    .SYNC_ENABLE("DISABLE"),
    .GMC_GAIN(0),
    .ICP_CURRENT(9),
    .KVCO(2),
    .LPF_CAPACITOR(2),
    .LPF_RESISTOR(8),
    .REFCLK_DIV(3),
    .FBCLK_DIV(4),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_DIV(15),
    .CLKC0_CPHASE(14),
    .CLKC0_FPHASE(0),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(3),
    .CLKC1_CPHASE(2),
    .CLKC1_FPHASE(0),
    .CLKC2_ENABLE("ENABLE"),
    .CLKC2_DIV(42),
    .CLKC2_CPHASE(41),
    .CLKC2_FPHASE(0) 
  ) pll_inst (
    .refclk(refclk),
    .reset(reset),
    .stdby(1'b0),
    .extlock(video_pll_open0),
    .load_reg(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(video_pll_open1),
    .dclk(1'b0),
    .dcs(1'b0),
    .dwe(1'b0),
    .di(8'b00000000),
    .daddr(6'b000000),
    .do({video_pll_open9, video_pll_open8, video_pll_open7, video_pll_open6, video_pll_open5, video_pll_open4, video_pll_open3, video_pll_open2}),
    .fbclk(clk0_out),
    .clkc({video_pll_open11, video_pll_open10, clk2_out, clk1_out, clk0_buf}) 
  );

endmodule

