--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/FPGA_isp/Anlogic_prj/mul_mov_check/prj/al_ip/blk_mem_gen_0.vhd
 -- Date	:	2022 10 29
 -- TD version	:	5.6.59063
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY blk_mem_gen_0 IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END blk_mem_gen_0;

ARCHITECTURE struct OF blk_mem_gen_0 IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_A	=> 10,
			ADDR_WIDTH_B	=> 10,
			DATA_DEPTH_A	=> 800,
			DATA_DEPTH_B	=> 800,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> '1',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '1',
			bea	=> (others=>'0'),
			web	=> '0',
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '1',
			rsta	=> '0',
			rstb	=> rstb,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
