/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/FPGA_isp/Anlogic_prj/mul_mov_check/prj/al_ip/ram2port.v
 ** Date	:	2022 11 03
 ** TD version	:	5.6.59063
\************************************************************/

`timescale 1ns / 1ps

module ram_2port ( 
	doa, dia, addra, clka, wea, rsta,ocea, 
	dob, dib, addrb, clkb, web, rstb, oceb
);


	parameter DATA_WIDTH_A = 32; 
	parameter ADDR_WIDTH_A = 8;
	parameter DATA_DEPTH_A = 256;
	parameter DATA_WIDTH_B = 32;
	parameter ADDR_WIDTH_B = 8;
	parameter DATA_DEPTH_B = 256;
	parameter REGMODE_A    = "OUTREG";
	parameter REGMODE_B    = "OUTREG";
	parameter WRITEMODE_A  = "READBEFOREWRITE";
	parameter WRITEMODE_B  = "READBEFOREWRITE";

	output [DATA_WIDTH_A-1:0] doa;
	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [DATA_WIDTH_B-1:0] dib;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  wea;
	input  web;
	input  clka;
	input  clkb;
	input  rsta;
	input  rstb;
	input  ocea;
	input  oceb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.MODE("DP"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib(dib),
				.addra(addra),
				.addrb(addrb),
				.cea(1'b1),
				.ceb(1'b1),
				.ocea(ocea),
				.oceb(oceb),
				.clka(clka),
				.clkb(clkb),
				.wea(wea),
				.web(web),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(rstb),
				.doa(doa),
				.dob(dob));


endmodule