--------------------------------------------------------------
 --  Copyright (c) 2011-2022 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/FPGA_isp/Anlogic_prj/mul_mov_check/prj/al_ip/ram2port.vhd
 -- Date	:	2022 11 03
 -- TD version	:	5.6.59063
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY ram_2port IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	wea	: IN STD_LOGIC;
	ocea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	rsta	: IN STD_LOGIC;

	dob	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
	dib	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
	addrb	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	web	: IN STD_LOGIC;
	oceb	: IN STD_LOGIC;
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END ram_2port;

ARCHITECTURE struct OF ram_2port IS

	BEGIN

	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 32,
			DATA_WIDTH_B	=> 32,
			ADDR_WIDTH_A	=> 8,
			ADDR_WIDTH_b	=> 8,
			DATA_DEPTH_A	=> 256,
			DATA_DEPTH_B	=> 256,
			MODE		=> "DP",
			REGMODE_A	=> "OUTREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "READBEFOREWRITE",
			WRITEMODE_B	=> "READBEFOREWRITE",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "9K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> dib,
			addra	=> addra,
			addrb	=> addrb,
			cea	=> '1',
			ceb	=> '1',
			ocea	=> ocea,
			oceb	=> oceb,
			clka	=> clka,
			clkb	=> clkb,
			wea	=> wea,
			web	=> web,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			rsta	=> rsta,
			rstb	=> rstb,
			doa	=> doa,
			dob	=> dob
		);

END struct;
